### ISSUE TITLE
Check the right filters when we change locale

### ISSUE THREAD

**Issue by MarionLeHerisson** [jolicode/jolitypo-website#21]
Some filters are belonging to a specific locale, like FrenchNoBreakSpace. 

I'd like to see this filter checked when I select French, and unchecked when I select something else. 

![image](https://user-images.githubusercontent.com/11477247/137689523-ec5433b3-f695-4727-954d-75ecd08430c0.png)

See if this situation applies with another locale 🤔

**Comment by lyrixx** [comment]
Do you want to work on this issue?

**Comment by lyrixx** [comment]
Fixed by #35 

Thanks
